services:
  - type: web
    name: torneo-bombonera
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.py:app
    disk:
      name: datos-torneo
      mountPath: /app/data
      sizeGB: 1
      